### ISSUE TITLE
Version 3.1.4 package timestamps are incorrect

### ISSUE THREAD

**Issue by mjbrook** [feross/typedarray-to-buffer#13]
When installing the latest version of this package through npm, a number of files have a timestamp of Jan 1 1970:

```
-rw-r--r-- 1 root root  758 Jan  1  1970 index.js
-rw-r--r-- 1 root root 1081 Jan  1  1970 LICENSE
drwxr-xr-x 3 root root 4096 Mar  6 10:10 node_modules
-rw-r--r-- 1 root root 2179 Mar  6 10:10 package.json
-rw-r--r-- 1 root root 3463 Jan  1  1970 README.md
drwxr-xr-x 2 root root 4096 Jan  1  1970 test
```

In my use case, this is causing issues when trying to package a project with this dependency using Python zip (`raise ValueError('ZIP does not support timestamps before 1980'`).

**Comment by feross** [comment]
Doesn't happen for me. If you find out anything else that helps me to reproduce the issue, please open a new issue.

**Comment by feross** [comment]
More info here: https://github.com/feross/typedarray-to-buffer/issues/14
