### ISSUE TITLE
Republish with updated NPM

### ISSUE THREAD

**Issue by sunrize531** [feross/typedarray-to-buffer#14]
The version of module which is currently published in npm registry appears to be affected by this npm bug:
https://github.com/npm/npm/issues/16734

Which prevents the application using this module (indirectly) from being deployed on Amazon AWS:
https://github.com/aws/aws-cli/issues/2639

Republishing the module using newer (or stable) version of npm should resolve the issue.

**Comment by feross** [comment]
Installed the latest Node.js LTS and npm and republished. Hope this fixes the issue for you.

```
node -v
v8.10.0

npm -v
5.7.1
```

Published as 3.1.5.
