### ISSUE TITLE
Support for float32Array?

### ISSUE THREAD

**Issue by binarykitchen** [feross/typedarray-to-buffer#2]
Any chance this can be enhanced to accept float32 arrays as an input before converting these to buffers?

**Comment by feross** [comment]
This already works with `Float32Array` objects, but probably not how you expect. From the readme:

> This module uses the typed array's underlying `ArrayBuffer` to back the new `Buffer`. This
> respects the "view" on the `ArrayBuffer`, i.e. `byteOffset` and `byteLength`. In other
> words, if you do `toBuffer(new Uint32Array([1, 2, 3]))`, then the new `Buffer` will
> contain `[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0]`, **not** `[1, 2, 3]`. And it still doesn't
> require a copy.

**Comment by feross** [comment]
You can do what you're probably trying to do like this:

``` js
var toBuffer = require('typedarray-to-buffer')
var a = new Float32Array([0, 1, 2])
var b = new Uint8Array(a.length)
for (var i = 0; i < a.length; i++) {
  b[i] = a[i]
}
var buf = toBuffer(b)
```

**Comment by binarykitchen** [comment]
I see. A Float32Array is not a typed array then?

If you look over at https://github.com/binarykitchen/videomail-client/blob/master/src/util/items/audioSample.js#L22 then you'll see why I am asking if this can be done within your module instead. You can see there that I am already using something similar to your code example.

**Comment by feross** [comment]
Float32Array is a typed array. But the way this module turns it into a buffer is by using the underlying representation of the ArrayBuffer. For floats that means that it's going to be the IEEE floating point representation.

**Comment by binarykitchen** [comment]
Hmmm, then maybe the name of this module should be a little more precise? This to avoid confusion ...

**Comment by feross** [comment]
Thanks for the suggestion, but the module name is just fine.
