### ISSUE TITLE
TypeError: constructor is not a function

### ISSUE THREAD

**Issue by binarykitchen** [feross/typedarray-to-buffer#3]
Seeing this with your latest version v3.0.5

**Comment by binarykitchen** [comment]
Guess because Buffer._augment is undefined

**Comment by binarykitchen** [comment]
Hmmm, you fixed that in commit e7d1e975baaedc5f9d871635c79c3b69423c7bb7 but why am I still having the older code?

**Comment by binarykitchen** [comment]
I have a guess. It's probably related to browserify.

The original code has:

```
  var constructor = Buffer.TYPED_ARRAY_SUPPORT
    ? function (arr) {
      arr.__proto__ = Buffer.prototype
      return arr
    }
    : function (arr) { return new Buffer(arr) }
```

After browserify I have this

```
  var constructor = Buffer.TYPED_ARRAY_SUPPORT
    ? Buffer._augment
    : function (arr) { return new Buffer(arr) }
```

Hmmm ...

**Comment by binarykitchen** [comment]
Ah, when I downgrade Browserify from v13 back to v12, then the above problem does not appear!

**Comment by feross** [comment]
If you're using browserify 13, you need to make sure that the latest version of `typedarray-to-buffer` (3.0.5) is used everywhere in your project. From @terinjokes's comment here (https://github.com/substack/node-browserify/issues/1482#issuecomment-171865570) you can see that 3.0.4 is being used.

**Comment by feross** [comment]
Actually, I'll just add back `Buffer._augment` for a while (until the next major version of buffer) to ease this transition period. You should be able to use browserify 13 and older versions of `typedarray-to-buffer` now.

Cheers!

**Comment by binarykitchen** [comment]
@feross thanks - yep i figured that out meanwhile. and easing the transition period is a good idea. maybe add a deprecation warning?
