### ISSUE TITLE
Fails in combination with Buffer module trying to test with Buffer.isBuffer

### ISSUE THREAD

**Issue by dignifiedquire** [feross/typedarray-to-buffer#5]
Given the following:

``` js
// global.Buffer should be the buffer module from npm
var array = new Uint8Array([1,2,3])
var buf = toBuffer(array)
assert(Buffer.isBuffer(buf)) // throws
```

The reason for this is that the `isBuffer` check checks for `._isBuffer` on the element but the code path on  here https://github.com/feross/typedarray-to-buffer/blob/master/index.js#L17-L19 does not add that property.

**Comment by feross** [comment]
Right you are. Sorry about that.

**Comment by feross** [comment]
Actually, what version of browserify are you using? The latest version of buffer (used in browserify 13) doesn't require setting `._isBuffer` manually on each instance since it's inherited through the prototype chain. See: https://github.com/feross/buffer/blob/master/index.js#L418

**Comment by dignifiedquire** [comment]
Arrrrggh -.- you are right the buffer version was outdated in one dependency (I'm using webpack for this one) updating it makes the issue go away.. Thanks.

**Comment by feross** [comment]
Hoping that by inheriting the whole prototype (i.e. Buffer is now a proper ES6 subclass of Uint8Array) we won't have version incompatibilities like this going forward. Sorry that this bit you though :(

**Comment by feross** [comment]
Actually, there's an even better solution. We can just stop depending on the internals of the browser buffer implementation since `new Buffer(arrayBuffer)` doesn't do a copy. See PR https://github.com/feross/typedarray-to-buffer/pull/6

**Comment by dignifiedquire** [comment]
#6 looks really good! thanks for the quick responses
